[build]
  command = "python build_site.py && npm install"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"
  API_KEY = "test-api-key"

# API endpoint redirects for cleaner URLs
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/api-health"
  status = 200

[[redirects]]
  from = "/api/scan"
  to = "/.netlify/functions/api-scan"
  status = 200

[[redirects]]
  from = "/api/extract"
  to = "/.netlify/functions/api-extract"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200